plugins:
    - jekyll-postcss-v2
postcss:
    cache: false
urls:
    authentication: /extension/authentication.json
    save: /extension/pages.json
    find: /extension/subscriptions/new.json
    subscribe: /extension/subscriptions/create.json
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - package.json
    - package-lock.json
    - gemfiles/
    - tmp/
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - postcss.config.js
    - CLAUDE.md
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
