plugins:
    - jekyll-postcss-v2
postcss:
    cache: false
urls:
    authentication: /extension/v1/authentication.json
    save: /extension/v1/pages.json
    find: /extension/v1/subscriptions/new.json
    subscribe: /extension/v1/subscriptions/create.json
    new_address: /extension/v1/addresses/new.json
    create_address: /extension/v1/addresses/create.json
    password_reset: /password_resets/new
exclude:
    - .sass-cache/
    - .jekyll-cache/
    - package.json
    - package-lock.json
    - gemfiles/
    - tmp/
    - Gemfile
    - Gemfile.lock
    - Rakefile
    - postcss.config.js
    - CLAUDE.md
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - bin/
    - Procfile
    - manifest.yml
