plugins:
  - jekyll-postcss-v2
postcss:
  cache: false
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - test
  - extension/views
  - package.json
  - package-lock.json
  - postcss.config.js
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
